[build]
  functions = "backend/functions"
  publish = "frontend/dist"
  command = "npm run build --prefix frontend"

[dev]
  port = 8888
  functions = "backend/functions"
  framework= "vue"
  command = "npm run client"

[functions]
  node_bundler = "esbuild"