[build]
  functions = "backend/functions"
  publish = "frontend/dist"
  command = "npm run build --prefix frontend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  targetPort = 3000
  port = 8888